### ISSUE TITLE
Script fails with Python 3 

### ISSUE THREAD

**Issue by IT-Yogi** [targendaz2/Mac-Set-Default-Apps#10]
Hi David, 

I really appreciate your script but got some issues with MacOS 12.3.1 and installed Python 3.10.4 from https://www.python.org/downloads/macos/.
I'm using the deployment via Jamf Script but it seems like python 3 isn't found because your script is poiting at /usr/bin/python which doesn't exists with python 3.10.4. I changed it to /usr/bin/python3 but this also fails. 
Did I miss something ?

/usr/bin/python
`Script result: sh: /Library/Application Support/JAMF/tmp/Mac Set Default Apps (MSDA): /usr/bin/python: bad interpreter: No such file or directory`

/usr/bin/python3
`Script result: Traceback (most recent call last):
  File "/Library/Application Support/JAMF/tmp/Mac Set Default Apps (MSDA)", line 471, in <module>
    sudo_command = '/usr/bin/sudo -u ' + username
TypeError: can only concatenate str (not "bytes") to str`

Cheers,
Jonny

**Comment by targendaz2** [comment]
Python no longer comes preinstalled on macOS. You'll need to install python3 before you can use MSDA on a Mac.

**Comment by IT-Yogi** [comment]
Hi David, 

Yes as I mentioned I installed python3 3.10.4 before executing your script, but it still fails?

**Comment by targendaz2** [comment]
Sorry, my bad. The script isn't python3 compatible. You'd need to install python2, although it's reached EOL.

**Comment by IT-Yogi** [comment]
Oh ok. I understand. 
Any chances for an update for python3?

**Comment by targendaz2** [comment]
I'll either update it to zsh or swift. Probably not python3.
