### ISSUE TITLE
macOS 12.3.1 - Python3

### ISSUE THREAD

**Issue by c-fulgencio** [targendaz2/Mac-Set-Default-Apps#11]
We are running into an issue. We currently have python3 installed via JAMF on our machines. It looks like the script is referencing python2 commands. Is there a workaround or an update so we can run the script with python3?

**Comment by targendaz2** [comment]
Not that I know of, but you're welcome to update the script and submit a pull request. I'm eventually planning on updating MSDA to Bash or Swift, but don't know when.

**Comment by Colonel-mustards** [comment]
I am after this as well @c-fulgencio did you find a workaround?  dont fancy trying to update the script on account of my lack of scripting skills...

**Comment by abalduccik** [comment]
I would really love someone to help get this working again, I relied on this to deploy my student machines and set google chrome as default. I work at a catholic school and it was amazing to have Jamf automatically set chrome as default for the kids.
