### ISSUE TITLE
adobe acrobat reader dc

### ISSUE THREAD

**Issue by threedotseven** [targendaz2/Mac-Set-Default-Apps#12]
hi,
I'm having issues setting adobe acrobat reader  as my default app using  "msda set com.adobe.acrobat.reader -u com.adobe.pdf all" command. it doesn't set acrobat reader dc as the default app and won't allow me to open pdfs in the preview app. when i installed adobe acrobat dc and used "msda set com.adobe.acrobat.pro -u com.adobe.pdf all" it sets adobe acrobat dc as the default app and able to open pdf files in the preview app as well. the endpoint i'm using to test is intel on big sur. please advise. thanks!

**Comment by targendaz2** [comment]
Hey, unfortunately I'm unable to help troubleshoot using MSDA. I recommend making sure you're using the right bundle ID's, extensions, and protocols. You could also try reaching out to the communities mentioned in the readme to see if other Mac Admins have had this issue.
