### ISSUE TITLE
Microsoft Teams as Tel default

### ISSUE THREAD

**Issue by Shanzaobrien** [targendaz2/Mac-Set-Default-Apps#14]
Hi all,

We are trying to use JAMF to add MS Teams as the default Tel app (because you need to sign into FaceTime to adjust the setting manually Augh). 

I found where the preference is kept in Mac OS and came up with the following parameter to push out in JAMF:
set com.microsoft.teams -p tel -u com.apple.launchservices.secure -feu

Could anyone help me why we are getting the following error code?

Executing Policy MS Teams default calling device script
--
Running script MSDA for TEL default to MS Teams...
Script exit code: 2
Script result: usage: MSDA for TEL default to MS Teams [-h] [--version] command ...MSDA for TEL default to MS Teams: error: too few arguments
Error running script: return code was 2.

Thanks :)

**Comment by targendaz2** [comment]
Hey, @Shanzaobrien. This seems like an information or implementation gap, given that the error is "too few arguments". I.e., the command you're using isn't being formatted correctly. If you still need help with this, check out the Mac SysAdmin communities I linked to in the readme.
