### ISSUE TITLE
error: argument command

### ISSUE THREAD

**Issue by alali16990** [targendaz2/Mac-Set-Default-Apps#18]
When I try to run the script, I get this error

_Executing Policy Default Adobe
--
Running script Mac Set Default Apps...
Script exit code: 2
Script result: usage: Mac Set Default Apps [-h] [--version] command ...Mac Set Default Apps: error: argument command: invalid choice: 'msda' (choose from 'set')
Error running script: return code was 2._

**Comment by targendaz2** [comment]
@alali16990 it looks like you're not running the command correctly. Check out the samples and the Mac Admin communities linked to in the readme.
