### ISSUE TITLE
If I try to run msda it tries to use python instead of python3

### ISSUE THREAD

**Issue by Mac-On** [targendaz2/Mac-Set-Default-Apps#19]
Hello,

the latest **MacSetDefaultApps-v1.3.1.pkg** is installed on the machine (latest macOS 14.5 Sonoma), also **python_recommended_signed-3.12.1.80742.pkg** from https://github.com/macadmins/python/releases/tag/v3.12.1.80742 is installed and works.

`msda` relies in `/usr/local/bin/msda`

and

`python3` relies in `/usr/bin/python3`

```
python3 --version
Python 3.9.6
```

If I try to run msda, it fails as it shows me the following:

`-sh: /usr/local/bin/msda: /usr/bin/python: bad interpreter: No such file or directory`

So it looks for `python` and not `python3` and I don't understand, why this happens and how to change it…

Thanks for help,
Marcel

PS: I know I could change this inside the `msda.py` file if I change the first line from

`#!/usr/bin/python`

to

`#!/usr/bin/python3`

but I'am wondering if there is not a better solution?

As `alias python=/usr/bin/python3` didn't worked for me on this machine…

**Comment by targendaz2** [comment]
The solution you proposed is how I'd recommend resolving the issue.

I'm working on version 2 that removes the dependency on Python. I don't have an ETA yet, but you can track my progress on the `jxa-v2` branch.

**Comment by Mac-On** [comment]
ok, good to know – thank you very much
