### ISSUE TITLE
Gets an error after runing the script via Jmaf

### ISSUE THREAD

**Issue by Blaban278** [targendaz2/Mac-Set-Default-Apps#3]
Hi @targendaz2 
Thanks for your help, I share with you the error I get.
<img width="1257" alt="Screen Shot 2021-07-27 at 9 50 40" src="https://user-images.githubusercontent.com/88029089/127128566-731ff966-0db5-4285-bc4e-7deba0a5bc20.png">

**Comment by Blaban278** [comment]
Operating System Version: 10.15.7

**Comment by targendaz2** [comment]
What's not working that you're trying to troubleshoot? Additionally, those logs don't look like they're from MSDA. Where did they come from?

**Comment by Blaban278** [comment]
Chrome not set as a default browser.
I'll check the logs again, they may not be related to the MSDA.
What else can I check?

**Comment by targendaz2** [comment]
I'm sorry you're running into an issue. The log you sent isn't from MSDA. MSDA's logs will show up in Jamf in the logs for the policy that runs it. If you see any errors in MSDA's logs, I can help troubleshoot.

**Comment by Blaban278** [comment]
Ok now it's works for me, Thanks for your help!
