### ISSUE TITLE
Issue with Monterey

### ISSUE THREAD

**Issue by gonzague** [targendaz2/Mac-Set-Default-Apps#6]
hello
Monterey uses Python 3 so when running the script, we get the following warning:

<img width="265" alt="Screen Shot 2021-09-29 at 12 57 04 PM" src="https://user-images.githubusercontent.com/932/144013463-38c2bf3a-06f4-4949-ba6c-bb05e93355e3.png">

Would there be a way to fix this ? Like detect the OS version and choose the compatible Python version? :-)

thanks!

**Comment by targendaz2** [comment]
I plan to update this app to Python 3 or Swift at some point, but I'm not sure when. For now, there's a config profile you can push that will disable this prompt.
