### ISSUE TITLE
Jamf Implementation Question

### ISSUE THREAD

**Issue by AlexT-byte** [targendaz2/Mac-Set-Default-Apps#7]
Hello, 
I have a question regarding the implementation of this package via Jamf. For the different arguments we would like to specify would all of them go into Parameter 4 (if so how would they be broken up Ie comma or just a space)? Or would they be broken up into Parameter 4,5,6 etc. 

For example, I would like to set the default apps to be Chrome and Microsoft Outlook, and Adobe Reader

**Comment by AlexT-byte** [comment]
Apologies I am a noob. We just started building out our Jamf/ Mac OS environment so I have limited knowledge regarding the Mac environment.

**Comment by targendaz2** [comment]
Hey, @AlexT-byte. The Usage section of the readme should be able to help you out.

**Comment by cyber-sec0** [comment]
How do I set the python script to default the browser to chrome?
I tried this but it gave me an error

![image](https://user-images.githubusercontent.com/91571849/157722700-2151487b-0a1c-4415-82b4-c589c3d15a70.png)

**Comment by targendaz2** [comment]
Hey, @cyber-sec0. It looks like you're trying to modify the script itself. That's not something I can help with. The readme gives examples for using the script to set the default browser to Chrome.
