### ISSUE TITLE
Question: How to set up the script on JAMF?

### ISSUE THREAD

**Issue by cyber-sec0** [targendaz2/Mac-Set-Default-Apps#8]
The readme is not clear enough for me.
Do I have to modify some part in the script itself or just make 2 scripts, first deploy the .py script then the script to set up an app as default?

**Comment by targendaz2** [comment]
@cyber-sec0 just to confirm, you've tried following the steps [linked here](https://github.com/targendaz2/Mac-Set-Default-Apps#as-a-jamf-script)?

**Comment by cyber-sec0** [comment]
Yes, my question is where do I set the command msda?
Is it somewhere inside the JAMF .py program, or do I first execute the .py program, then create another policy executing the msda command?

**Comment by targendaz2** [comment]
Hey, @cyber-sec0 the readme does answer those questions. I suggest posting on Jamf Nation or the Mac Admins Slack if you need help setting up a Jamf script with parameters.

If you run into any bugs with MSDA, I can help you out. I unfortunately can't help with general Jamf/Mac topics.
